### ISSUE TITLE
Password not properly encoded on login

### ISSUE THREAD

**Issue by qurben** [csrdelft/onontdekt#66]
Passwords and usernames containing special characters such as `&` result in an error when logging in because the values are not html encoded.

**Comment by Manduro** [comment]
Fixed in v2.0.1

**Comment by Boudewijn26** [comment]
Are emoji now supported as well? 🎉 ?

**Comment by Manduro** [comment]
Afaik browsers don't support passwords with emoji.

**Comment by Boudewijn26** [comment]
I can type the 🎉 in the [w3schools password field](https://www.w3schools.com/html/html_form_input_types.asp)

**Comment by qurben** [comment]
Emoji work. (And probably worked before).
